### ISSUE TITLE
Pydantic UUID4 doesn't work

### ISSUE THREAD

**Issue by heindrickdumdum0217** [wallneradam/esorm#10]
Environment
```
Pydantic == 2.8.2
pyesorm == 0.4.8
```

```
from esorm import ESModel
from pydantic import UUID4


class A(ESModel)
    uuid: UUID4
```

It throws the following error.
```
ValueError: Unknown ES field type: <class 'uuid.UUID'>
```

**Comment by wallneradam** [comment]
Not all Pydantic type is supported, because there is no UUID field in elasticsearch.
UUID is an object, not a base type. I will investigate if these types could be converted to base types easily.

**Comment by wallneradam** [comment]
It is working in the new version (v0.5.0).
