### ISSUE TITLE
Pydantic HttpUrl doesn't work

### ISSUE THREAD

**Issue by heindrickdumdum0217** [wallneradam/esorm#14]
Environment
```
Pydantic == 2.8.2
pyesorm == 0.5.0
```

Got the following error.
```
errors=(
  TypeError(
    "Unable to serialize Url('https://xxx.yyy.com/images/thumbnails/114496/d3uHiMWrKfQufRvPe6cC9Ttcr9rc2e0Amzi5boS1') (type: <class 'pydantic_core._pydantic_core.Url'>)")
  )
)
```

**Comment by wallneradam** [comment]
Could you please share your model, which cause the problem? Becase I have [test](https://github.com/wallneradam/esorm/blob/27160396042f3925b575ea00b47acba5c29a1b22/tests/test_esorm.py#L362) for a  [model with HttpUrl](https://github.com/wallneradam/esorm/blob/27160396042f3925b575ea00b47acba5c29a1b22/tests/conftest.py#L90) and it works.

**Comment by heindrickdumdum0217** [comment]
```
Class User(ESModel):
    avatar_image_url: HttpUrl


class Comment(ESModel):
    id: unsigned_long
    url: HttpUrl
    user: User
```

I think the error happens in `User` model.

**Comment by wallneradam** [comment]
I've just tested:
```python
async def test():
    import esorm
    from pydantic import HttpUrl
    from esorm.fields import unsigned_long

    class User(esorm.ESModel):
        avatar_image_url: HttpUrl

    class Comment(esorm.ESModel):
        id: unsigned_long
        url: HttpUrl
        user: User

    await esorm.setup_mappings()
    
    doc = Comment(id=1, url='http://example.com', 
                  user=User(avatar_image_url='https://xxx.yyy.com/images/thumbnails/114496'))
    doc_id = await doc.save()
    assert doc_id is not None
```
This just works.

Are you sure you using v0.5.0?

**Comment by wallneradam** [comment]
Can I close this issue?

**Comment by heindrickdumdum0217** [comment]
It still throws bugs, but I'm not sure it's `Pydantic` bug or `esorm` issue.
As my brief checking, it happens when receive encoded urls.

**Comment by wallneradam** [comment]
Ok, I close this for now, as I think it is fixed in the new version according to my tests. I used exactly your model, and it works.
