### ISSUE TITLE
Request for IP field type

### ISSUE THREAD

**Issue by poppelaars** [wallneradam/esorm#18]
Could you add support for the IP field type?

Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/ip.html
Pydantic: https://docs.pydantic.dev/latest/api/networks/#pydantic.networks.IPvAnyAddress

**Comment by wallneradam** [comment]
Yes, It should not be hard... I'm going to do it soon.

**Comment by wallneradam** [comment]
It is done.
