### ISSUE TITLE
Hosts should be optional in connect function

### ISSUE THREAD

**Issue by heindrickdumdum0217** [wallneradam/esorm#21]
https://github.com/wallneradam/esorm/blob/main/esorm/esorm.py#L37

hosts parameter should be optional in the connect function.
In the underlying library [(elasticsearch-py)](https://github.com/elastic/elasticsearch-py), we can connect using cloud_id and api_key.

If I pass empty hosts, it throws the following error.

```
from esorm import connect


async def init_es():
    await connect(
        hosts=[],
        cloud_id="cloud_id",
        api_key="api_key"
    )
```

```
ValueError: The 'cloud_id' and 'hosts' parameters are mutually exclusive
```

If I pass `None` to hosts parameter it works, but `Pycharm` shows typing  warning and fail in `mypy`.

The following screenshot is from the [elasticsearch-py](https://elasticsearch-py.readthedocs.io/en/v8.14.0/quickstart.html) documentation.
![image](https://github.com/user-attachments/assets/b5fa1743-b7a4-4ebf-ab81-09eb56786e2c)

**Comment by wallneradam** [comment]
It is solved in v0.6.1.
