### ISSUE TITLE
Optional[PositiveInt] doens't work

### ISSUE THREAD

**Issue by heindrickdumdum0217** [wallneradam/esorm#8]
Environment
```
Pydantic == 2.8.2
pyesorm == 0.4.7
```

```
from typing import Optional

from esorm import ESModel
from pydantic import PositiveInt


class A(ESModel)
    age: Optional[PositiveInt]
```

It throws the following error.
```
ValueError: Unknown ES field type: typing.Annotated[int, Gt(gt=0)]
```

It works with `PositiveInt`, but doens't work with `Optional[PositiveInt]`

**Comment by wallneradam** [comment]
Thanks for reporting this.
I created a new version, according to my tests it should sove this issue. Please check it.

**Comment by heindrickdumdum0217** [comment]
@wallneradam 

Thank you for your reply and great work.
Even the repository has not much stars, I think it has great potential.

**Comment by wallneradam** [comment]
Though using `PositiveInt` may not be fully optimized, because in ES it will use signed integer, because `PositiveInt` is just `typing.Annotated[int, Gt(gt=0)]`, which is an `int`. Integer is mapped to ES type `long`. So if `0` is allowed, you can use the new `unsigned_int` type from Esorm instead.

**Comment by wallneradam** [comment]
Sorry, `unsigned_long` is the right one, and it is in the documentation.

**Comment by heindrickdumdum0217** [comment]
But it says unsigned_log is not declared in `__all__`

**Comment by wallneradam** [comment]
Yes, I've forgotten to add it to the __all__ of the module. It will be in the next release, soon. Though it should still work, I think.

**Comment by wallneradam** [comment]
Ok, `unsigned_long` is in `__all__` in the latest (v0.5.0) version.
